name: crystal-puzzle # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Crystal Puzzle Quest
summary: Unlock the power of crystals.
description: Solve intricate puzzles by connecting crystals and unleashing their magical powers.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  crystal-puzzle:
    command: bin/crystal-puzzle-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  crystal-puzzle:
    plugin: dump
    source: .
    organize:
      crystal-puzzle-bin: bin/
